# Generated by Django 5.0.4 on 2024-04-24 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade_entrada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade_saida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_almoxarifado.material'),
        ),
    ]
