# Generated by Django 5.0.4 on 2024-04-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0002_estoque_data_entrada_estoque_data_saida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade_entrada',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantidade_saida',
        ),
        migrations.AlterField(
            model_name='estoque',
            name='material',
            field=models.CharField(max_length=100),
        ),
    ]
