# Generated by Django 5.0.4 on 2024-04-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0003_remove_estoque_data_entrada_and_more'),
    ]

    operations = [
    ]
