# Generated by Django 5.0.4 on 2024-04-24 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0004_auto_20240424_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_almoxarifado.material'),
        ),
    ]
