# Generated by Django 5.0.4 on 2024-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0006_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
