# Generated by Django 5.0.4 on 2024-04-24 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_almoxarifado', '0007_alter_estoque_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
